<?php
/**
 * @file
 * Code for the GSB Feature Featured Person FPP feature.
 */

include_once 'gsb_feature_featured_person_fpp.features.inc';

/**
 * Implements hook_entity_alter().
 */
function gsb_feature_featured_person_fpp_entity_info_alter(&$entity_info) {
  $entity_info['fieldable_panels_pane']['bundles']['featured_person'] = array(
    'label' => t('Featured Person'),
    'pane category' => t('GSB panes'),
    'pane top level' => TRUE, // set to true to make this show as a top level icon
    'admin' => array(
      'path' => 'admin/structure/fieldable-panels-panes/manage/%fieldable_panels_panes_type',
      'bundle argument' => 4,
      // Note that this has all _ replaced with - from the bundle name.
      'real path' => 'admin/structure/fieldable-panels-panes/manage/featured-person',
      'access arguments' => array('administer fieldable panels panes'),
    ),
  );
}

/**
 * Implements hook_preprocess_HOOK() for fieldable-panels-pane.tpl.php.
 */
function gsb_feature_featured_person_fpp_preprocess_fieldable_panels_pane(&$variables) {
  if ($variables['elements']['#bundle'] != 'featured_person') {
    return;
  }

  // Add classes based on the display style.
  try {
    $wrapper = entity_metadata_wrapper('fieldable_panels_pane', $variables['elements']['#element']);
    $variables['output']['title'] = $wrapper->field_title->value();
    $person = $wrapper->field_person_fac_single_ref;
    $image = $person->field_image_single_public->value();
    $variables['output']['title'] = $wrapper->field_title->value();
    $name = array();
    $name[] = $person->field_salutation->value();
    $name[] = $person->field_first_name->value();
    $name[] = $person->field_middle_name->value();
    $name[] = $person->field_last_name->value();
    $variables['output']['name'] = implode(' ', $name);
  }
  catch (EntityMetadataWrapperException $e) {
  }
}
